### ISSUE TITLE
Bad state: No element

### ISSUE THREAD

**Issue by Adrift001** [luckysmg/flutter_swipe_action_cell#40]
```
When the exception was thrown, this was the stack: 
#0      List.first (dart:core-patch/growable_array.dart:332:5)
#1      SwipeActionCellState._closeNestedAction (package:flutter_swipe_action_cell/core/cell.dart:661:33)
#2      SwipeActionCellState._scrollListener (package:flutter_swipe_action_cell/core/cell.dart:415:7)
#3      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:308:24)
#4      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:412:5)
#5      ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:884:25)
#6      ScrollPositionWithSingleContext.beginActivity (package:flutter/src/widgets/scroll_position_with_single_context.dart:114:11)
#7      ScrollPositionWithSingleContext.drag (package:flutter/src/widgets/scroll_position_with_single_context.dart:264:5)
```

```
canEdit ? [
                    SwipeAction(
                        title: '编辑',
                        onTap: (CompletionHandler handler) async {
                          editAction?.call();
                        },
                        color: Colors.amber),
                  ] : []
```
滚动的时候报错

**Comment by luckysmg** [comment]
给一个最小化可复现的demo一下，我这里运行一下看看

**Comment by Adrift001** [comment]
链接: https://pan.baidu.com/s/1ZVXdldjfW70_H8thDI0Z0w 提取码: kdy9 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by luckysmg** [comment]
收到

**Comment by luckysmg** [comment]
试一下最新master分支，应该是没有问题了，另外，你的代码里面key里面装index是不行的哈，必须装你model里对应的数据的哈

**Comment by Adrift001** [comment]
好的.

**Comment by luckysmg** [comment]
没有问题了说一声哈，我打新版本发布上pub

**Comment by Adrift001** [comment]
没问题了.

**Comment by luckysmg** [comment]
ok,那我上2.1.5

**Comment by Adrift001** [comment]
好的, 然后我再试试, 没问题就不给你回复了.

**Comment by luckysmg** [comment]
pub上传了，不过可能要过会儿才能pub get到哈

**Comment by Adrift001** [comment]
好的
